#!/bin/sh /etc/rc.common

# Values are consumed by /etc/rc.common.
# shellcheck disable=SC2034
START=95
# shellcheck disable=SC2034
STOP=10
# shellcheck disable=SC2034
USE_PROCD=1

start_service() {
	config_load opencellid
	local enabled
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/opencellid-agent daemon
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/opencellid
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger opencellid
	config_load opencellid
	local iface
	config_get iface main wwan_interface wwan
	procd_open_trigger
	procd_add_interface_trigger "interface.*.up" "$iface" /etc/init.d/opencellid restart
	procd_close_trigger
}
